name: 'cache'

on:
  push:
    paths:
      - 'run.sh'
      - 'cli/*'
      - 'test_pnr.sh'
      - '.github/workflows/cache.yml'
      - 'dockerfiles/cache_*'
      - 'dockerfiles/synth_formal'
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:

  gtkwave:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v1
    - run: |
        python -m pip install -r cli/requirements.txt
        ./cli/cli.py task gtkwave
    - name: Deploy to hub.docker.com
      run: ./run.sh all

  pnr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v1
    - run: |
        python -m pip install -r cli/requirements.txt
        ./cli/cli.py task pnr
    - name: Deploy to hub.docker.com
      run: ./run.sh all

  yosys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v1
    - run: |
        python -m pip install -r cli/requirements.txt
        ./cli/cli.py task yosys
    - name: Deploy to hub.docker.com
      run: ./run.sh all

  formal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v1
    - run: |
        python -m pip install -r cli/requirements.txt
        ./cli/cli.py task formal
    - name: Deploy to hub.docker.com
      run: ./run.sh all

  symbiyosys:
    needs: [ yosys, formal ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v1
    - run: |
        python -m pip install -r cli/requirements.txt
        ./cli/cli.py task symbiyosys
    - name: Deploy to hub.docker.com
      run: ./run.sh all

  test:
    needs: [ pnr, yosys ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./test_pnr.sh
