name: 'ext'

on:
  push:
    paths:
      - 'run.sh'
      - 'cli/*'
      - '.github/workflows/ext.yml'
      - 'dockerfiles/ls_debian'
      - 'dockerfiles/gui'
  schedule:
    - cron: '0 0 * * 3,6'

env:
  DOCKER_BUILDKIT: 1
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:

  ls:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        task: [ debian, ubuntu ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build images
      run: ./run.sh -l $TASK
      env:
        TASK: ${{ matrix.task }}
    - name: Deploy to hub.docker.com
      run: ./run.sh ext

  gui:
    needs: [ ls ]
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v1
    - run: |
        python -m pip install -r cli/requirements.txt
        ./cli/cli.py task gui
    - name: Deploy to hub.docker.com
      run: ./run.sh ext

