name: 'synth'

on:
  push:
    paths:
      - 'run.sh'
      - 'cli/*'
      - '.github/workflows/synth.yml'
      - 'dockerfiles/synth_*'
  schedule:
    - cron: '0 0 * * 3,6'

env:
  DOCKER_BUILDKIT: 1
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:

  synth:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build images
      run: ./run.sh -s
    - name: Deploy to hub.docker.com
      run: ./run.sh synth
