name: 'vunit'

on:
  push:
    paths:
      - 'run.sh'
      - 'cli/*'
      - '.github/workflows/vunit.yml'
      - 'dockerfiles/vunit'
  schedule:
    - cron: '0 0 * * 3,6'

env:
  DOCKER_BUILDKIT: 1
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:

  vunit:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v1
    - run: |
        python -m pip install -r cli/requirements.txt
        ./cli/cli.py task vunit
    - name: Deploy to hub.docker.com
      run: ./run.sh vunit
